# -*- coding: utf-8 -*-
"""BART.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRB3CDnZBCwxcuqDPONyauJ0gN85nciY
"""

!pip install -q transformers datasets accelerate scikit-learn

# prompt: mount google drive

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Changing to the working directory
# %cd drive/MyDrive/Colab Notebooks/email_classification
!ls

!pwd

"""## Text file -> Dataframe"""

import zipfile
import os

zip_path = 'AI Training Dataset.zip'
extract_path = '/data'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import pandas as pd

csv_path = os.path.join(extract_path, 'label.csv')
df = pd.read_csv(csv_path)

# Select Small Dataset
range1 = list(range(8, 58))       # 8~57 Pass
range2 = list(range(901, 951))    # 901~950 Fail

selected_filenames = [f"email{i}.txt" for i in range1 + range2]

df = df[df['filename'].isin(selected_filenames)].reset_index(drop=True)

# Create 'text' column
texts = []
for fname in df['filename']:
    file_path = os.path.join(extract_path, fname)
    with open(file_path, 'r', encoding='utf-8') as f:
        texts.append(f.read())

df['text'] = texts

# df.head() # idx | filename | status | text
df = df[['text', 'status']]
df.rename(columns={'status': 'label'}, inplace=True)  # Rename status -> label; for the use of HuggingFace Trainer or datasets.Dataset
df.head()

"""## Train Test Split"""

from sklearn.model_selection import train_test_split

# train / temp (val + test)
train_df, temp_df = train_test_split(
    df, test_size=0.3, stratify=df['label'], random_state=42
)

# temp → validation / test
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, stratify=temp_df['label'], random_state=42
)

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

"""## Call Model and Tokenizer"""

from transformers import BartTokenizer, BartForSequenceClassification

model_name = 'facebook/bart-base'
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForSequenceClassification.from_pretrained(model_name, num_labels=2)

def tokenize(batch):
    return tokenizer(batch['text'], truncation=True, padding='max_length', max_length=256)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

# label → labels
for ds in [train_dataset, val_dataset, test_dataset]:
    ds = ds.rename_column("label", "labels")

"""## Trainer Setting"""

from transformers import TrainingArguments, Trainer, TrainerCallback
from sklearn.metrics import accuracy_score
import numpy as np

def compute_metrics(pred):
    labels = pred.label_ids
    preds = np.argmax(pred.predictions[0] if isinstance(pred.predictions, tuple) else pred.predictions, axis=1)
    return {"accuracy": accuracy_score(labels, preds)}

training_args = TrainingArguments(
    output_dir='./gpt2_results',
    eval_strategy="epoch",
    save_strategy="no",
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    seed=42,
    logging_dir="./logs",
    report_to="none"  # Disable all integrations, including WandB
)

# Define a custom callback to disable WandB logging
class DisableWandbCallback(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        # Do nothing to disable logging
        pass

# Create an instance of the custom callback
disable_wandb_callback = DisableWandbCallback()

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[disable_wandb_callback]
)

import os
os.environ["WANDB_DISABLED"] = "true"

trainer.train()

trainer.evaluate(test_dataset)

results = trainer.predict(test_dataset)
print("Test Accuracy:", results.metrics['test_accuracy'])

predictions = trainer.predict(test_dataset)

logits = predictions.predictions
predicted_labels = np.argmax(logits, axis=1)

true_labels = predictions.label_ids

# Fetch text
# test_dataset (HuggingFace Dataset) -> to_pandas() convert
df_test = test_dataset.to_pandas()

# Add label column
df_test['true_label'] = true_labels
df_test['predicted_label'] = predicted_labels

# Print N samples
sample_n = 10
print(df_test[['text', 'true_label', 'predicted_label']].sample(sample_n))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_true = predictions.label_ids
y_pred = np.argmax(predictions.predictions, axis=1)

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Class 0", "Class 1"])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()