# -*- coding: utf-8 -*-
"""DistilBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-v4cdVeLZB_DeNXeKfwNSB1cVs2UFAxc
"""

!pip install -q transformers datasets accelerate scikit-learn

# prompt: mount googld drive

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Changing to the working directory
# %cd drive/MyDrive/Colab Notebooks/email_classification
!ls

!pwd

"""## Text file -> Dataframe"""

import zipfile
import os

zip_path = 'AI Training Dataset.zip'  # 파일 업로드 후 이 경로로 지정됨
extract_path = '/data'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

import pandas as pd

csv_path = os.path.join(extract_path, 'label.csv')
df = pd.read_csv(csv_path)

# Select Small Dataset
range1 = list(range(8, 58))       # 8~57 Pass
range2 = list(range(901, 951))    # 901~950 Fail

selected_filenames = [f"email{i}.txt" for i in range1 + range2]

df = df[df['filename'].isin(selected_filenames)].reset_index(drop=True)

# Create 'text' column
texts = []
for fname in df['filename']:
    file_path = os.path.join(extract_path, fname)
    with open(file_path, 'r', encoding='utf-8') as f:
        texts.append(f.read())

df['text'] = texts

# df.head() # idx | filenamd | status | text
df = df[['text', 'status']]
df.rename(columns={'status': 'label'}, inplace=True)  # Rename status -> label; for the use of HuggingFace Trainer or datasets.Dataset
df.head()

"""## Train Test Split"""

from sklearn.model_selection import train_test_split

# 1단계: 먼저 train / temp (val + test) 나누기
train_df, temp_df = train_test_split(
    df, test_size=0.3, stratify=df['label'], random_state=42
)

# 2단계: temp → validation / test 나누기
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, stratify=temp_df['label'], random_state=42
)

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

from transformers import AutoTokenizer

model_name = 'distilbert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(batch['text'], truncation=True, padding='max_length', max_length=256)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

# Rename 'label' → 'labels'(for Trainer compatibility)
train_dataset = train_dataset.rename_column("label", "labels")
val_dataset = val_dataset.rename_column("label", "labels")
test_dataset = test_dataset.rename_column("label", "labels")

"""## Model Implementation"""

from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer, TrainerCallback
from sklearn.metrics import accuracy_score
import numpy as np

# 모델 로딩
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# 평가 메트릭 정의
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {"accuracy": accuracy_score(labels, predictions)}

# 학습 설정
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="no",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    seed=42,
    logging_dir="./logs",
    report_to="none"  # Disable all integrations, including WandB
)

# Define a custom callback to disable WandB logging
class DisableWandbCallback(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        # Do nothing to disable logging
        pass

# Create an instance of the custom callback
disable_wandb_callback = DisableWandbCallback()

# Trainer 생성
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
    callbacks=[disable_wandb_callback]
)

import os
os.environ["WANDB_DISABLED"] = "true"

trainer.train()

results = trainer.predict(test_dataset)
print("Test Accuracy:", results.metrics['test_accuracy'])

predictions = trainer.predict(test_dataset)

logits = predictions.predictions
predicted_labels = np.argmax(logits, axis=1)

true_labels = predictions.label_ids

# Fetch text
# test_dataset (HuggingFace Dataset) -> to_pandas() convert
df_test = test_dataset.to_pandas()

# Add label column
df_test['true_label'] = true_labels
df_test['predicted_label'] = predicted_labels

# Print N samples
sample_n = 10
print(df_test[['text', 'true_label', 'predicted_label']].sample(sample_n))

# Show wrongly classified samples only

pred_labels = np.argmax(predictions.predictions, axis=1)

# 테스트셋 DataFrame으로 변환
test_df = test_dataset.to_pandas()

# 실제 라벨과 예측 라벨 추가
test_df['true_label'] = predictions.label_ids
test_df['predicted_label'] = pred_labels

# ❌ 잘못 분류된 것만 필터링
wrong_preds = test_df[test_df['true_label'] != test_df['predicted_label']]

# 🔍 상위 10개 확인
wrong_preds[['text', 'true_label', 'predicted_label']].head(10)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_true = predictions.label_ids
y_pred = np.argmax(predictions.predictions, axis=1)

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Class 0", "Class 1"])
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()